version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - hypery2k
  assignees:
  - hypery2k
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.1
    - 5.36.0
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
    - 5.1.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
    - 7.23.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: jasmine
    versions:
    - 3.6.4
    - 3.7.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: ini
    versions:
    - 1.3.8
