sudo: required
dist: trusty
language: node_js
node_js:
  - "12"
  - "14"
services:
  - docker
install:
  - npm run clean
before_script:
  - pip install --user -r test/setup/test-requirements.txt
script:
   - npm run build
   - npm run jasmine-test
   - docker build -t toolisticon/ssl-hostinfo-prometheus-exporter .
   - (cd test/setup && docker-compose up -d)
   - travis_retry pytest test/end2end/test_*.py
   - travis_retry curl -s localhost:9000 | docker exec -i prometheus promtool check metrics
