sudo: required
dist: trusty
language: node_js
node_js:
  - "14"
  - "16"
services:
  - docker
install:
  - npm run clean
script:
   - npm run build
   - npm run jasmine-test
   - docker build -t toolisticon/ssl-hostinfo-prometheus-exporter .
